[pytest]
testpaths = testcase
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -vs
norecursedirs = .git .venv venv node_modules allure-results allure-report report logs tmp_*
filterwarnings =
    ignore:Unverified HTTPS request is being made:urllib3.exceptions.InsecureRequestWarning
