[pytest]
testpaths = tests_blackbox_api
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -vs
norecursedirs = .git .venv venv node_modules reports logs artifacts
filterwarnings =
    ignore:Unverified HTTPS request is being made:urllib3.exceptions.InsecureRequestWarning
