timeout: 15
verify_ssl: false

auth:
  login_page_url: /amcs/login
  login_submit_url: /sso/ajaxcheck

home:
  init_menu_url: /home/initMenu
  dict_list_url_prefix: /home/listDictNoRoot

menu:
  user_menu_tree_url: /menu/getUserMenuTree

plugin:
  find_plugin_url: /plugin/findPlugin

video:
  camera_tree_url: /video/v1/cameraTree
  preset_cameras_url: /preset/getCameras

patrol:
  patrol_card_list_url: /amcs/patrol/card/list
  patrol_plan_list_url: /amcs/patrol/plan/findPatrolPlanVoList

alarm:
  alarm_record_page_url: /alarmRecord/getPageData2

history:
  monitor_link_history_url: /amcs/monitorLink/findHistoryPage

gis:
  d2_data_path_url: /amcs/gis2d/getD2DataPath
  d2_map_prop_url: /amcs/gis3d/getMapProp
  d3_map_prop_url: /amcs/gis3d/get3dMapProp
  d3_gis_config_url: /amcs/gis3d/getGisConfig

rdac:
  station_list_url: /rdac/subList
  station_items_page_url: /rdac/items
  station_item_list_url: /rdac/itemList

system:
  sys_logo_url: /amcs/getSysLogo
  alarm_count_url: /amcs/realTimeAlarm/alarmCount
  timestamp_url: /amcs/getTimestamp
  health_url: /amcs/info/amcsHealth

database:
  monitor_page_url: /monitor/page
  monitor_validate_url: /monitor/validateMonitor
  monitor_save_url: /monitor/saveOrUpdate
  monitor_can_delete_url: /monitor/canDeleteMonitor/
  monitor_delete_url: /monitor/deleteMonitorByIds
  monitor_edit_page_url: /monitor/toEditPage
  monitor_import_page_url: /monitor/openImportPage
  monitor_xml_export_url: /monitor/exportXml
  monitor_template_download_url: /amcs/excel_2019/downloadTemp
  monitor_excel_import_url: /amcs/excel_2019/import
  monitor_excel_export_url: /amcs/excel_2019/export
  monitor_related_equip_url: /amcs/monitorArea/queryEquipPresetList
  monitor_camera_list_url: /amcs/monitorArea/queryCameraList
  monitor_preset_list_url: /amcs/monitorArea/preset/list
